name: app_solutely
description: "Welcome to [Your YouTube Channel Name]! We're dedicated to providing high-quality tutorials and guides for building mobile app solutions using Flutter. Whether you're a beginner looking to get started with Flutter or an experienced developer seeking advanced techniques, our channel has something for everyone."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter






  cupertino_icons: ^1.0.6

  shared_preferences: ^2.2.2
  get: ^4.6.6     # In this tutorial, we will be leveraging the GetX architecture. Therefore, make sure to import the latest GetX package.

dev_dependencies:
  flutter_test:
    sdk: flutter











  flutter_lints: ^3.0.0




flutter:







  uses-material-design: true


























































